spring.application.name=piversionbd
spring.datasource.url=jdbc:mysql://localhost:3306/pidb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuration JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Port du serveur
server.port=8081

# Mail Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yasminesabbaghsabbagh@gmail.com
spring.mail.password=bqds eara admg aenn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${spring.mail.username}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT
security.jwt.secret=change-this-secret-change-this-secret-change-this
security.jwt.expiration-ms=3600000
